plugins {
    id 'java-library'
    id 'eclipse'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
    id 'net.darkhax.curseforgegradle' version '1.1.15'
    id 'com.modrinth.minotaur' version '2.+'
}
version = MC_VERSION + '-' + MOD_VERSION
group = 'carbonconfiglib' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = 'CarbonConfig-Neoforge'
jarJar.enable()



// Mojang ships Java 17 to end users in 1.18+, so your mod should target Java 17.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets {
    main {
        java {
 			srcDir "carbonconfig/src/main/java"
 			srcDir "src/main/java"
 		}
    }
}

runs {
    configureEach {
        modSource project.sourceSets.main
        //Required for JIJ iirc.
		dependencies {
    		runtime ':Primitive Collections-0.8.9'
    	}
    }
    client {}
    server {
        programArgument '--nogui'
    }
    gameTestServer {}
    data {
        programArguments.addAll '--mod', "carbonconfig", '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
	maven {
        url = "https://www.cursemaven.com"
    }
    flatDir {
       dirs("libs")
   	}
}


dependencies {
    implementation "net.neoforged:neoforge:21.1.228"
	implementation ':Primitive Collections-0.8.9'
	implementation "curse.maven:jei-238222:7420587"
	jarJar(group: 'com.github.Speiger', name: 'Primitive Collections', version: '[0.8,0.9)') {
	 	jarJar.pin(it, "0.8.9")
	}
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

test {
	exclude 'carbonconfiglib/**'
}

tasks.jarJar {
    archiveClassifier.set("all")
    eachFile { fcd ->
        if (fcd.relativePath.pathString.startsWith("assets/carbonconfig/lang/") && !fcd.name.endsWith(".json")) {
        	fcd.exclude()
        }
    }
    doLast {
        def jarFile = archiveFile.get().asFile
        def newJar = new File(jarFile.parent, jarFile.name.replace("-all", ""))
        
        if (newJar.exists()) newJar.delete() // make sure no conflict
        jarFile.renameTo(newJar)
    }
}

task publishMods() {
	group 'publishing'
	description 'Publishes the mod to all Mod Distributors'
	doLast {
		System.out.println("Published Mods to Curseforge/Modrinth")
	}
}
publishMods.dependsOn('modrinth')
publishMods.dependsOn('curseforge')

modrinth {
	token = System.getenv("Modrinth_API_Token");
	projectId = 'carbon-config'
	versionName = archivesBaseName.replace(" ", "")+"-"+version
	versionNumber = MOD_VERSION
	versionType = RELEASE_TYPE
	uploadFile = jar
	gameVersions = [MC_VERSION]
	loaders = ['neoforge']
	
    def logs = new File(projectDir, "/changelogs/"+MOD_VERSION.replace(".", "")+".md");
    changelog = logs.exists() ? logs.getText('UTF-8') : "";
}

task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) { 
	mustRunAfter assemble
	group 'publishing'
	description 'Publishes the mod to Curseforge'
	apiToken = System.getenv("Curseforge_API_Token")
		
	def mainFile = upload(898104, jar)
    mainFile.releaseType = RELEASE_TYPE
    mainFile.displayName = archivesBaseName.replace(" ", "")+"-"+version
    
    def changelog = new File(projectDir, "/changelogs/"+MOD_VERSION.replace(".", "")+".md");
    mainFile.changelog = changelog.exists() ? changelog.getText('UTF-8') : "";
    mainFile.changelogType = 'markdown'
    mainFile.addGameVersion(MC_VERSION, '1.21.1', 'Server', 'Client')
    mainFile.addJavaVersion('Java 21')
	mainFile.addModLoader('NeoForge')
}