# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.16.5
	yarn_mappings=1.16.5+build.10
	loader_version=0.15.7

# Mod Properties
	maven_group = carbonconfig
	archives_base_name = CarbonConfig-Fabric
	MC_VERSION = 1.16.5
	MOD_VERSION = 2.0.0
	RELEASE_TYPE = release

# Dependencies
	fabric_version=0.42.0+1.16
