modLoader="javafml"
loaderVersion="[43,)"
license="Apache-2.0"
[[mods]]
	modId="carbonconfig"
	version="${file.jarVersion}"
	displayName="Carbon Config Library"
	displayURL="https://github.com/Carbon-Config-Project/CarbonConfig"
	logoFile="carbonconfig.png"
	credits="Thanks to the IC2Classic team for open sourcing this"
	authors="Meduris, Speiger"
	description='''
		Carbon Config is IC2Classics Config Implementation made open source
	'''
	[[dependencies.carbonconfig]]
		modId="forge"
		mandatory=true
		versionRange="[43,)"
		ordering="NONE"
		side="BOTH"
	[[dependencies.carbonconfig]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.19.2,1.20)"
		ordering="NONE"
		side="BOTH"